In [1]:
print("Jupyter 커널 연결 확인!")
import pandas as pd, numpy as np, matplotlib, seaborn as sns
print("pandas:", pd.__version__)
print("numpy:", np.__version__)

Jupyter 커널 연결 확인!
pandas: 3.0.5
numpy: 2.5.2

In [15]:
from dotenv import load_dotenv
import os
load_dotenv()
oracle_user = os.getenv("ORACLE_USER")
oracle_password = os.getenv("ORACLE_PASSWORD")
oracle_dsn = os.getenv("ORACLE_DSN")

In [19]:
import oracledb
import pandas as pd

USER = oracle_user
PASSWORD = oracle_password
DSN = oracle_dsn

conn = oracledb.connect(user=USER, password = PASSWORD, dsn = DSN)
print("Oracle 연결 성공")


query = "SELECT * FROM DELIVERY_ORDERS"
df = pd.read_sql(query, conn)
print(df.shape)
df.head()

Oracle 연결 성공
(7, 7)

/var/folders/4j/qgl7j0hx7y33d7l5bjgf9h9h0000gn/T/ipykernel_9149/2105918086.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   ORDER_ID MENU_NAME CATEGORY  PRICE  RATING REGION ORDER_DATE
0         1       떡볶이       분식   9000     4.5    강남구 2026-08-01
1         2        치킨       치킨  22000     4.8    서초구 2026-08-02
2         3        피자       피자  25000     4.2    강남구 2026-08-03
3         4       짜장면       중식   8000     4.0    송파구 2026-08-04
4         5       마라탕       중식  13000     4.6    강남구 2026-08-05

In [21]:
with oracledb.connect(user = oracle_user, password=oracle_password, dsn= oracle_dsn) as conn:
    df = pd.read_sql("SELECT * FROM DELIVERY_ORDERS", conn)
    # with문 블록을 벗어나는 순간 자동으로 conn.close() 호출되어 안정적임

print("연결 및 쿼리 성공! 데이터 shape:", df.shape)
df.head()

연결 및 쿼리 성공! 데이터 shape: (7, 7)

/var/folders/4j/qgl7j0hx7y33d7l5bjgf9h9h0000gn/T/ipykernel_9149/1346653605.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM DELIVERY_ORDERS", conn)

   ORDER_ID MENU_NAME CATEGORY  PRICE  RATING REGION ORDER_DATE
0         1       떡볶이       분식   9000     4.5    강남구 2026-08-01
1         2        치킨       치킨  22000     4.8    서초구 2026-08-02
2         3        피자       피자  25000     4.2    강남구 2026-08-03
3         4       짜장면       중식   8000     4.0    송파구 2026-08-04
4         5       마라탕       중식  13000     4.6    강남구 2026-08-05